services:
  - type: web
    name: my-rails-api
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails server
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:ATbrAAIjcDFlMzhiYjFiYjQ4MDE0N2RjODc5NjA3OTljMTdkNTRmNXAxMA@close-seal-14059.upstash.io:6379

  - type: worker
    name: sidekiq-worker
    env: ruby
    plan: free
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:ATbrAAIjcDFlMzhiYjFiYjQ4MDE0N2RjODc5NjA3OTljMTdkNTRmNXAxMA@close-seal-14059.upstash.io:6379

databases:
  - name: my-db
    plan: free
