services:
  - type: web
    name: my-rails-api
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails server
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString

databases:
  - name: my-db
    plan: free
